on: [ push ]
name: CI

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
